"""worker oauth token

Revision ID: 93a6b609f7e3
Revises: cef593906d68
Create Date: 2026-09-22 08:02:11.459308

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93a6b609f7e3"
down_revision: str | Sequence[str] | None = "cef593906d68"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workers", sa.Column("oauth_token_enc", sa.LargeBinary(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workers", "oauth_token_enc")
    # ### end Alembic commands ###
