"""job attachment keys

Revision ID: cef593906d68
Revises: 45190ce9de1e
Create Date: 2026-09-22 02:10:49.649693

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cef593906d68"
down_revision: str | Sequence[str] | None = "45190ce9de1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # autogenerate 產的是 nullable=False 但沒有 server default —— 那樣在有既有
    # 資料列的表上會直接失敗。先帶著 default 加上去，再把 default 拿掉：
    # 之後的寫入都由應用層給值，schema 不需要記著這個預設。
    op.add_column(
        "jobs",
        sa.Column(
            "attachment_keys",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.alter_column("jobs", "attachment_keys", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "attachment_keys")
    # ### end Alembic commands ###
